### ISSUE TITLE
miner crashes/doesnt launch

### ISSUE THREAD

**Issue by Ahmad-Drak** [MoneroOcean/hiveos#1]
Hi,
I setup the miner as indicated in your blog. I launch the flight sheet and no errors are reported. On the rig, a miner is created (3412.miner) and then dies immediately.

MIner settings:
![mo1](https://user-images.githubusercontent.com/8726349/109222650-0ff0e500-77ba-11eb-8bf7-6e6bd428b0f5.PNG)
![mo2](https://user-images.githubusercontent.com/8726349/109221046-ae307b00-77b9-11eb-8f61-92a6e122c8df.PNG)
 

On the rig, I can see the directory of mo_xmrig `/root/hive/miners/custom/mo_xmrig` and includes all the files

![mo3](https://user-images.githubusercontent.com/8726349/109222088-ed5ecc00-77b9-11eb-8690-f02ae4d63032.PNG)

Any ideas whats happening?

**Comment by MoneroOcean** [comment]
Can you please show "miner log" command output?

**Comment by Ahmad-Drak** [comment]
`
> Unpacking /hive/miners/custom/downloads/mo_xmrig-v6.9.0-mo1.tar.gz
mo_xmrig/
mo_xmrig/h-stats.sh
mo_xmrig/readme.txt
mo_xmrig/config_global.json
mo_xmrig/h-manifest.conf
mo_xmrig/h-config.sh
mo_xmrig/config.json
mo_xmrig/h-stop.sh
mo_xmrig/h-run.sh
mo_xmrig/xmrig
chown: cannot access '/hive/miners/custom/mo_xmrig-v6.9.0': No such file or directory
sed: can't read /hive/miners/custom/mo_xmrig-v6.9.0/h-manifest.conf: No such file or directory
sed: can't read /hive/miners/custom/mo_xmrig-v6.9.0/h-config.sh: No such file or directory
sed: can't read /hive/miners/custom/mo_xmrig-v6.9.0/h-run.sh: No such file or directory
sed: can't read /hive/miners/custom/mo_xmrig-v6.9.0/h-stats.sh: No such file or directory
> Sending "danger": Unable to install miner from https://github.com/MoneroOcean/hiveos/raw/main/mo_xmrig-v6.9.0-mo1.tar.gz
{"method":"message","jsonrpc":"2.0","id":0,"params":{"rig_id":"1237728","passwd":"********","type":"danger","data":"Unable to install miner from https://github.com/MoneroOcean/hiveos/raw/main/mo_xmrig-v6.9.0-mo1.tar.gz"}}

> Miner screen is not running`

**Comment by MoneroOcean** [comment]
I see. looks like it is issue with extra dash in tar.gz archive name. You can temporary use https://github.com/MoneroOcean/hiveos/raw/main/mo_xmrig-6.8.2_mo1.tar.gz while I'm fixing this.

**Comment by Ahmad-Drak** [comment]
yea that works. Thanks!

**Comment by Ahmad-Drak** [comment]
@MoneroOcean does the mo_gminer only mine etherium? Doesnt it run a benchmark test to check which algorithms are best just like mo_xmrig?

**Comment by MoneroOcean** [comment]
It can mine several coins (ETH, RVN, XWP and TUBE) and yes it benchmarks them like mo_xmrig to auto switch to the best algo for your hardware.

**Comment by MoneroOcean** [comment]
BTW You can try to see if https://github.com/MoneroOcean/hiveos/raw/main/mo_xmrig-v6.9.0_mo1.tar.gz works fine now (replaced -mo1 to _mo1).

**Comment by Ahmad-Drak** [comment]
Yes it works now. Thanks.

For the gminer, it doesnt seem to do any benchmarks.

` Miner:   custom
mo_gminer
https://github.com/MoneroOcean/hiveos/raw/main/mo_gminer-2.44.tar.gz
Already installed
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version (8.10.0~dfsg-2ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 57 not upgraded.
>>> Meta Miner v4.2
!!! Config file /hive/miners/custom/mo_gminer/mm.json does not exists
!!! Ignoring unknown option '/run/hive/miners/custom/mo_gminer_mm.json'
>>> Checking miner configurations (make sure they all configured to connect to 127.0.0.1:3333 pool)
+----------------------------------------------------------------+
|                          GMiner v2.44                          |
+----------------------------------------------------------------+
Algorithm:          Ethash
DevFee:             0.65%
Stratum server:     
  host:             localhost:3333
  user:             46Tok2ugRFsbiRcn6zJBcqC295Z5tD669RFTpFSppc2jDt3ohDB9Z483C6NGHUzH42JYB7xvQbR8uSkYspHLLzCvH7xVXvq
  password:         x
Power calculator:   on
Color output:       on
Watchdog:           on
API:                http://127.0.0.1:42010
Log to file:        /var/log/miner/custom/mo_gminer.log
Selected devices:   GPU0
Intensity:          100 
Temperature limits: 90C 
------------------------------------------------------------------
00:49:35 Failed to initialize miner on GPU0: ASUS GeForce GTX 780 Ti 3GB [0000:05:00.0]: no kernel image is available for execution on the device
00:49:35 No devices for mining
 `

**Comment by MoneroOcean** [comment]
mo_gminer will likely not work well for 3GB card. Just mine RVN on it (use ~kawpow in pass and other RVN miner options like usual)

**Comment by Ahmad-Drak** [comment]
I tried putting ~kawpow in pass and even specifying kawpoe in the algorithm field, but it was still same output as above..

**Comment by MoneroOcean** [comment]
Are using using mo_gminer? Try usual gminer, but without "--proto stratum" and replace ethash by kawpow:

![image](https://user-images.githubusercontent.com/33983510/109231930-467d2e80-77bf-11eb-8ad5-222f6d598eaa.png)

**Comment by Ahmad-Drak** [comment]
sorry for late reply, I was just able to get back to it.
I tried mo_gminer and the 'normal' gminer. I also used the settings you suggested, i get this error

12:52:07 Failed to initialize miner on GPU0: ASUS GeForce GTX 780 Ti 3GB [0000:05:00.0]: no kernel image is available for execution on the device
 Is this related to limited vram?

**Comment by MoneroOcean** [comment]
Yes. Likely your OS does not leave enough RAM for kawpow to be mined. Technically 3GB RAM should be still enough.
